meta:
  display: My pipeline

args:
  # sets default values
  myArg: myValue

stages:
  # stages are completed sequentially
  - display: Build my thing
    # tasks are completed concurrently, if possible
    tasks:
      - myTask

  - display: upload the thing
    tasks:
      - upload