meta:
  display: My pipeline

args:
  # sets default values
  branch: main

stages:
  # stages are completed sequentially
  - display: Build my thing
    # tasks are completed concurrently, if possible
    tasks:
      - myTask

  #- display: upload the thing
    #tasks:
      #- upload